# ==== Сборка приложения ====
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ==== Продакшн-образ ====
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Забираем из standalone-папки полностью готовый сервер + депенденции
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Ставим только прод-зависимости
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev

EXPOSE 3000
CMD ["node", "server.js"]
